[tools]
python = "3.14.0"
uv = "latest"

[settings]
python.uv_venv_auto = true

[tasks.run]
description = 'Run Site Generator'
run = "./main.sh"

[tasks.test]
description = 'Test Site Generator'
run = "./test.sh"

[tasks.start-server]
description = 'Start Local Server'
run = "python3 -m http.server 8888 -d public"
